### ISSUE TITLE
Cannot finish install 

### ISSUE THREAD

**Issue by suunee** [donadigo/eddy#88] opened 2020-07-08 23:58 UTC
No, all you need to do is:
    git clone https://github.com/donadigo/eddy.git
    cd eddy
    mkdir build && cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    sudo make install

    That's it.

Hello, i followed exactly those steps but i keep having this error... im using ZorinOS Core, any help?
"CMake Error: The source directory "/home/leansune" does not appear to contain CMakeLists.txt."

**Comment by donadigo** [comment] 2020-07-09 00:38
Make sure that you're in the build directory like this `/home/leansune/eddy/build` before doing `cmake ..` and make sure that each previous command didn't fail for some reason.

**Comment by donadigo** [comment] 2020-11-28 14:10
Closing since the issue is no more active.

**Closed by donadigo** 2020-11-28 14:10 UTC
